{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-common",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exoplayer-common-2.17.1.aar",
          "url": "exoplayer-common-2.17.1.aar",
          "size": 345673,
          "sha512": "a6095e47013fd0982e205115207c5e691cdab77cf5396292486d64e142cd6be4bcc9f13e8c012ee77042080e179dd25e179debe0e1968d817f633fefda6a2e7d",
          "sha256": "91cd486d422c53e28a33f8a90d9c3f38fe102f8b1539a346d5c15cb0eb140277",
          "sha1": "63d983a9540bb8f380306a15c5a824d8406bd22e",
          "md5": "5e2f42f0918d99680a9257aab2e19885"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exoplayer-common-2.17.1.aar",
          "url": "exoplayer-common-2.17.1.aar",
          "size": 345673,
          "sha512": "a6095e47013fd0982e205115207c5e691cdab77cf5396292486d64e142cd6be4bcc9f13e8c012ee77042080e179dd25e179debe0e1968d817f633fefda6a2e7d",
          "sha256": "91cd486d422c53e28a33f8a90d9c3f38fe102f8b1539a346d5c15cb0eb140277",
          "sha1": "63d983a9540bb8f380306a15c5a824d8406bd22e",
          "md5": "5e2f42f0918d99680a9257aab2e19885"
        }
      ]
    }
  ]
}
