{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-ui",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-ui-2.17.1.aar",
          "url": "exoplayer-ui-2.17.1.aar",
          "size": 448789,
          "sha512": "e9dd84b32ab0c8a5c3fc2a4f4fea518f89e327194b3025287ecc56a31047128e128af5ab9b68f09b661af027de78c36396950695a921c0ca484215498a409342",
          "sha256": "d6c67d88973b48392fb8a3b140416bf86d9fa62754f1623c1dcb627185471919",
          "sha1": "71e595d092a210f88d9ed4143caa633e06eb7d88",
          "md5": "773ea09d571c9a3ffef5d4a613b74c99"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-ui-2.17.1.aar",
          "url": "exoplayer-ui-2.17.1.aar",
          "size": 448789,
          "sha512": "e9dd84b32ab0c8a5c3fc2a4f4fea518f89e327194b3025287ecc56a31047128e128af5ab9b68f09b661af027de78c36396950695a921c0ca484215498a409342",
          "sha256": "d6c67d88973b48392fb8a3b140416bf86d9fa62754f1623c1dcb627185471919",
          "sha1": "71e595d092a210f88d9ed4143caa633e06eb7d88",
          "md5": "773ea09d571c9a3ffef5d4a613b74c99"
        }
      ]
    }
  ]
}
