{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "extension-okhttp",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "extension-okhttp-2.17.1.aar",
          "url": "extension-okhttp-2.17.1.aar",
          "size": 10351,
          "sha512": "f264ffca2a436ea02f2043e97cdb587376414d501049ea37d572ad2e28e9d48821f56d5aa8bffd2caf49f3d32e479cd24ceea2bb250fdda419e21105569cf4c9",
          "sha256": "55815c4630915fa59c917e5678972b2d7356c7762b3fa3e785378da8716b6446",
          "sha1": "f4f4dc51f4ea51451be6e2eb2671f17381db8774",
          "md5": "af883ef8ba1a4f62d89c6c26df487719"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "extension-okhttp-2.17.1.aar",
          "url": "extension-okhttp-2.17.1.aar",
          "size": 10351,
          "sha512": "f264ffca2a436ea02f2043e97cdb587376414d501049ea37d572ad2e28e9d48821f56d5aa8bffd2caf49f3d32e479cd24ceea2bb250fdda419e21105569cf4c9",
          "sha256": "55815c4630915fa59c917e5678972b2d7356c7762b3fa3e785378da8716b6446",
          "sha1": "f4f4dc51f4ea51451be6e2eb2671f17381db8774",
          "md5": "af883ef8ba1a4f62d89c6c26df487719"
        }
      ]
    }
  ]
}
