{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-decoder",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-decoder-2.17.1.aar",
          "url": "exoplayer-decoder-2.17.1.aar",
          "size": 17005,
          "sha512": "3539d1078118db0e2911b28ed248b628617f71edb0e08f6fc0047a9bd6fa01f5b22fe3fa3d6d06d879d96220fde3753a5290176a0ecf9a86a86fe36e6b931213",
          "sha256": "4ea652818b704cbb1c46cc37ebc7b864d3d4a70037e93e6c7c3599fbaf2f3d66",
          "sha1": "2d03932915f54a426716d868f20ce24b2026ab30",
          "md5": "34947ce669ec2c1b431fd9513857498b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-decoder-2.17.1.aar",
          "url": "exoplayer-decoder-2.17.1.aar",
          "size": 17005,
          "sha512": "3539d1078118db0e2911b28ed248b628617f71edb0e08f6fc0047a9bd6fa01f5b22fe3fa3d6d06d879d96220fde3753a5290176a0ecf9a86a86fe36e6b931213",
          "sha256": "4ea652818b704cbb1c46cc37ebc7b864d3d4a70037e93e6c7c3599fbaf2f3d66",
          "sha1": "2d03932915f54a426716d868f20ce24b2026ab30",
          "md5": "34947ce669ec2c1b431fd9513857498b"
        }
      ]
    }
  ]
}
