{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-smoothstreaming",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-smoothstreaming-2.17.1.aar",
          "url": "exoplayer-smoothstreaming-2.17.1.aar",
          "size": 46634,
          "sha512": "66ca2740319f03ade6d5b986e0825bc690323429d57a6a4233bcd8a601d5f2ac5977f9dc6832fb8168fb36a2ac38f673b3cd49115ef75933ded453f8a2041c67",
          "sha256": "d740c31fe05984bd82f4cc3b1f2247347d61e690e2520d5ba50e682e742a530f",
          "sha1": "02e5d58446bf2865a68a0beabb3cd7bed949b015",
          "md5": "9e209fe57e7c65635932558d91623895"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-smoothstreaming-2.17.1.aar",
          "url": "exoplayer-smoothstreaming-2.17.1.aar",
          "size": 46634,
          "sha512": "66ca2740319f03ade6d5b986e0825bc690323429d57a6a4233bcd8a601d5f2ac5977f9dc6832fb8168fb36a2ac38f673b3cd49115ef75933ded453f8a2041c67",
          "sha256": "d740c31fe05984bd82f4cc3b1f2247347d61e690e2520d5ba50e682e742a530f",
          "sha1": "02e5d58446bf2865a68a0beabb3cd7bed949b015",
          "md5": "9e209fe57e7c65635932558d91623895"
        }
      ]
    }
  ]
}
