{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-database",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-database-2.17.1.aar",
          "url": "exoplayer-database-2.17.1.aar",
          "size": 7416,
          "sha512": "18fac58b0a9f0b49a90102eada522c558788bbe6026ff6d7f32be27098341fca8daa7a287e04962eef30876505538eac351f36db47e0d310168421150e8908d4",
          "sha256": "c450571cfc805d0ea7f31487791e4c1704b374a030ac82f203f1512a209eb6d5",
          "sha1": "0aced8abbfa363fc9c983916cb85d953e74f758f",
          "md5": "7b25732d7205f677f1e4c62ff500238b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-database-2.17.1.aar",
          "url": "exoplayer-database-2.17.1.aar",
          "size": 7416,
          "sha512": "18fac58b0a9f0b49a90102eada522c558788bbe6026ff6d7f32be27098341fca8daa7a287e04962eef30876505538eac351f36db47e0d310168421150e8908d4",
          "sha256": "c450571cfc805d0ea7f31487791e4c1704b374a030ac82f203f1512a209eb6d5",
          "sha1": "0aced8abbfa363fc9c983916cb85d953e74f758f",
          "md5": "7b25732d7205f677f1e4c62ff500238b"
        }
      ]
    }
  ]
}
