{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-core",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.17.1.aar",
          "url": "exoplayer-core-2.17.1.aar",
          "size": 1154872,
          "sha512": "695e6182a41bf53a6079be9b83c1aad0c74e0d65d9fb1953d438984db16aaa64883b726bd7a4ce977bfcee3184b12bc310d5447985ff2f402c1a750d019025c1",
          "sha256": "68f450cdef834bbe7fc2a8ed43dc08c676f1e230704e1c3e33e879937944182d",
          "sha1": "b0708ae4b8de12488cdf54bdabfdf7bb19ed213f",
          "md5": "990d9b91e6078881015a0b1301dd0e98"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-datasource",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-extractor",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-core-2.17.1.aar",
          "url": "exoplayer-core-2.17.1.aar",
          "size": 1154872,
          "sha512": "695e6182a41bf53a6079be9b83c1aad0c74e0d65d9fb1953d438984db16aaa64883b726bd7a4ce977bfcee3184b12bc310d5447985ff2f402c1a750d019025c1",
          "sha256": "68f450cdef834bbe7fc2a8ed43dc08c676f1e230704e1c3e33e879937944182d",
          "sha1": "b0708ae4b8de12488cdf54bdabfdf7bb19ed213f",
          "md5": "990d9b91e6078881015a0b1301dd0e98"
        }
      ]
    }
  ]
}
