{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-extractor",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-extractor-2.17.1.aar",
          "url": "exoplayer-extractor-2.17.1.aar",
          "size": 693462,
          "sha512": "e4585997ad931092e7ea2f11c3bc59138947d3d1b277bfe6e2f6e8f04dbac0196ac637e3ff0a6bbd08019e6a2279ea3ce29e792b869d76c58e9dea8d13f780d7",
          "sha256": "2e1f6d1babf7fa9c9532c3e33d812e39e041d23cfaa8819d6481402efe5c2212",
          "sha1": "ef6b0ca37d5ddac4a3fd5ec680e8e0402667b6fa",
          "md5": "5180131057e5a53bc70b9ed8cd8d1cc6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-extractor-2.17.1.aar",
          "url": "exoplayer-extractor-2.17.1.aar",
          "size": 693462,
          "sha512": "e4585997ad931092e7ea2f11c3bc59138947d3d1b277bfe6e2f6e8f04dbac0196ac637e3ff0a6bbd08019e6a2279ea3ce29e792b869d76c58e9dea8d13f780d7",
          "sha256": "2e1f6d1babf7fa9c9532c3e33d812e39e041d23cfaa8819d6481402efe5c2212",
          "sha1": "ef6b0ca37d5ddac4a3fd5ec680e8e0402667b6fa",
          "md5": "5180131057e5a53bc70b9ed8cd8d1cc6"
        }
      ]
    }
  ]
}
