{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media",
    "module": "media",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-1.4.3.aar",
          "url": "media-1.4.3.aar",
          "size": 342828,
          "sha512": "90a9419a261be2539bc38a277796c9bc8e18de7f069d572af6ff3a231be18cbd7ee7e83611dadd61210cc5e70e649ad7546ba9f42d5fecc8bcb49b1ada74a4f7",
          "sha256": "89a83d648dafeb5160a76dcdf996735d746f410c115166cf15693b5208d73d95",
          "sha1": "25b724518cddfea0a691db5332db450ddde4e62e",
          "md5": "cf2dafad2cea9e66bdb23bc05cc9aa8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-1.4.3.aar",
          "url": "media-1.4.3.aar",
          "size": 342828,
          "sha512": "90a9419a261be2539bc38a277796c9bc8e18de7f069d572af6ff3a231be18cbd7ee7e83611dadd61210cc5e70e649ad7546ba9f42d5fecc8bcb49b1ada74a4f7",
          "sha256": "89a83d648dafeb5160a76dcdf996735d746f410c115166cf15693b5208d73d95",
          "sha1": "25b724518cddfea0a691db5332db450ddde4e62e",
          "md5": "cf2dafad2cea9e66bdb23bc05cc9aa8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media-1.4.3-sources.jar",
          "url": "media-1.4.3-sources.jar",
          "size": 144018,
          "sha512": "cc49a982f56332d1fc7fea08683b9cac1da2d1ceae9e1d803bb70e795b4136e64b5c2961f2cdfbd0798b4749e1f249d5cef008d3ba77a325e7a29c64eedb31d2",
          "sha256": "1a2ebabcf173448d0c38183c90b1777849408ce785202c78826b683202e42865",
          "sha1": "afcc8d588f12441525a86fe2d479ed95212c8174",
          "md5": "55bca53c480ddcc6377f3d6a22de0800"
        }
      ]
    }
  ]
}
