{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-dash",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-dash-2.17.1.aar",
          "url": "exoplayer-dash-2.17.1.aar",
          "size": 130391,
          "sha512": "26cf6e2b3ac513267051fe37d1f6aabd682a094f2b4e56faf4bc99cf065026e0fea242c6043b04c18198edcd94ebb46f1b4cd23d96732bb65c39cab86419e818",
          "sha256": "57feb330b7d346a89ecf564ce5249cbdb6b08832337fef53fd2852a974d59429",
          "sha1": "fc48474b06649a5de1ec3082a14dce733138349d",
          "md5": "b24948cb800b81f5a00dd57e0619a9e5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-dash-2.17.1.aar",
          "url": "exoplayer-dash-2.17.1.aar",
          "size": 130391,
          "sha512": "26cf6e2b3ac513267051fe37d1f6aabd682a094f2b4e56faf4bc99cf065026e0fea242c6043b04c18198edcd94ebb46f1b4cd23d96732bb65c39cab86419e818",
          "sha256": "57feb330b7d346a89ecf564ce5249cbdb6b08832337fef53fd2852a974d59429",
          "sha1": "fc48474b06649a5de1ec3082a14dce733138349d",
          "md5": "b24948cb800b81f5a00dd57e0619a9e5"
        }
      ]
    }
  ]
}
