{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-datasource",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-datasource-2.17.1.aar",
          "url": "exoplayer-datasource-2.17.1.aar",
          "size": 141484,
          "sha512": "f9fdc469e564f17c68eab9b90e3e742152468c692d301346d67b7e49221910b08bc3387922772d8085f55fbb5d5ecffabe7ad6786e1e2a2244e27662773bbc7c",
          "sha256": "214128d3c03a479e0268ca90b98197f505f49c3440187e9dbb0ae21d6031b9c2",
          "sha1": "d25b56c6310e76115a855e5888dca19f4feedaee",
          "md5": "f392e0e5b6200b9c726e673609ff172d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-database",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-datasource-2.17.1.aar",
          "url": "exoplayer-datasource-2.17.1.aar",
          "size": 141484,
          "sha512": "f9fdc469e564f17c68eab9b90e3e742152468c692d301346d67b7e49221910b08bc3387922772d8085f55fbb5d5ecffabe7ad6786e1e2a2244e27662773bbc7c",
          "sha256": "214128d3c03a479e0268ca90b98197f505f49c3440187e9dbb0ae21d6031b9c2",
          "sha1": "d25b56c6310e76115a855e5888dca19f4feedaee",
          "md5": "f392e0e5b6200b9c726e673609ff172d"
        }
      ]
    }
  ]
}
