{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.startup",
    "module": "startup-runtime",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "startup-runtime-1.1.0.aar",
          "url": "startup-runtime-1.1.0.aar",
          "size": 18737,
          "sha512": "ea257459532eb88f989400a9b547b3b422c7bca26133507f785cb69883277a6e5195339233ac14cf30cc7c1364e3cb799750d162f1958c535940a0d1603b767c",
          "sha256": "a171885822aefd51417e6a2a5e15a8a6e9d311054a20e18d50039bafc9a039e7",
          "sha1": "81bcda4796c33c557622c22b8570c32fa72dad78",
          "md5": "204c659a23e3b0516a51156e9228a3b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "startup-runtime-1.1.0.aar",
          "url": "startup-runtime-1.1.0.aar",
          "size": 18737,
          "sha512": "ea257459532eb88f989400a9b547b3b422c7bca26133507f785cb69883277a6e5195339233ac14cf30cc7c1364e3cb799750d162f1958c535940a0d1603b767c",
          "sha256": "a171885822aefd51417e6a2a5e15a8a6e9d311054a20e18d50039bafc9a039e7",
          "sha1": "81bcda4796c33c557622c22b8570c32fa72dad78",
          "md5": "204c659a23e3b0516a51156e9228a3b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "startup-runtime-1.1.0-sources.jar",
          "url": "startup-runtime-1.1.0-sources.jar",
          "size": 6443,
          "sha512": "634d04d368a300a23aead01a5b879b79f46b756373aa7de87b26da57be174e624ef15383c4a92e20fd38746c01be5cfb58fcfbf0e080cc5525ab2bae0f29bab1",
          "sha256": "00809d39aa10344a1a750693b601993afe2208fe4585da49c72e8066c061a9b0",
          "sha1": "4c05087ef4fd7e8d60dde42edf0225195d3a12fd",
          "md5": "595a2736e393d421f4ef131becd8ac94"
        }
      ]
    }
  ]
}
