{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-ui",
    "version": "2.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-ui-2.16.0.aar",
          "url": "exoplayer-ui-2.16.0.aar",
          "size": 445286,
          "sha512": "cfde0038b0210dbf16338a1ad6c3a03883bd6f37d434721a07d0b389e634495dbffa8e516d012af4b80cadeb731e183db0faf0047868836d7dff7eafc7d96eb5",
          "sha256": "e83828f17ee220a7ec537637305993a7df288c3f791970a2b99f4a4f5e506b43",
          "sha1": "a4c74e029de36e084bcc5812508460a70f09fafd",
          "md5": "d30d65a0c697ed492c9cf6c0e86fa804"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-ui-2.16.0.aar",
          "url": "exoplayer-ui-2.16.0.aar",
          "size": 445286,
          "sha512": "cfde0038b0210dbf16338a1ad6c3a03883bd6f37d434721a07d0b389e634495dbffa8e516d012af4b80cadeb731e183db0faf0047868836d7dff7eafc7d96eb5",
          "sha256": "e83828f17ee220a7ec537637305993a7df288c3f791970a2b99f4a4f5e506b43",
          "sha1": "a4c74e029de36e084bcc5812508460a70f09fafd",
          "md5": "d30d65a0c697ed492c9cf6c0e86fa804"
        }
      ]
    }
  ]
}
