{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-hls",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-hls-2.17.1.aar",
          "url": "exoplayer-hls-2.17.1.aar",
          "size": 158190,
          "sha512": "f0936c8470d9b914478e1bb33012b7f80eaa7e2d78a07f3c9faf0ff8931c05d8839eedf67e0ca392969032a6897ef9db6c3d35e5cfb2da1d4b53b2148af79538",
          "sha256": "5038138781d04d1c23fc280335043c6c91ea9eda3bf3cbe6d2af5d6e7f1da672",
          "sha1": "f9107413528d6306b027febacb7302396577b1a5",
          "md5": "cd7dd3d415aa1b4b29fe1367176ddb55"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-hls-2.17.1.aar",
          "url": "exoplayer-hls-2.17.1.aar",
          "size": 158190,
          "sha512": "f0936c8470d9b914478e1bb33012b7f80eaa7e2d78a07f3c9faf0ff8931c05d8839eedf67e0ca392969032a6897ef9db6c3d35e5cfb2da1d4b53b2148af79538",
          "sha256": "5038138781d04d1c23fc280335043c6c91ea9eda3bf3cbe6d2af5d6e7f1da672",
          "sha1": "f9107413528d6306b027febacb7302396577b1a5",
          "md5": "cd7dd3d415aa1b4b29fe1367176ddb55"
        }
      ]
    }
  ]
}
